[rospy.client][INFO] 2023-04-22 15:35:07,941: init_node, name[/rostopic_10930_1682148907851], pid[10930]
[xmlrpc][INFO] 2023-04-22 15:35:07,943: XML-RPC server binding to 127.0.0.1:0
[xmlrpc][INFO] 2023-04-22 15:35:07,945: Started XML-RPC server [http://localhost:35685/]
[rospy.init][INFO] 2023-04-22 15:35:07,945: ROS Slave URI: [http://localhost:35685/]
[rospy.impl.masterslave][INFO] 2023-04-22 15:35:07,946: _ready: http://localhost:35685/
[rospy.registration][INFO] 2023-04-22 15:35:07,947: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2023-04-22 15:35:07,948: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2023-04-22 15:35:08,046: registered with master
[rospy.rosout][INFO] 2023-04-22 15:35:08,047: initializing /rosout core topic
[rospy.rosout][INFO] 2023-04-22 15:35:08,055: connected to core topic /rosout
[rospy.simtime][INFO] 2023-04-22 15:35:08,063: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2023-04-22 15:35:08,171: topic[/cmd_vel] adding connection to [http://localhost:46739/], count 0
[rospy.internal][INFO] 2023-04-22 15:35:08,263: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2023-04-22 15:35:53,323: signal_shutdown [signal-2]
[rospy.internal][INFO] 2023-04-22 15:35:53,342: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2023-04-22 15:35:53,343: topic[/cmd_vel] removing connection to http://localhost:46739/
[rospy.internal][WARNING] 2023-04-22 15:35:53,346: Unknown error initiating TCP/IP socket to localhost:40105 (http://localhost:46739/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2023-04-22 15:35:53,350: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2023-04-22 15:35:53,351: signal-2
[rospy.core][INFO] 2023-04-22 15:35:53,460: signal_shutdown [atexit]
